# PyTorch 

In [1]:
import torch
import numpy as np

In [3]:
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]
t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


In [4]:
n = np.ones(5)
t = torch.from_numpy(n)

np.add(n, 1, out=n)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]


In [5]:
data = [[1, 2],[3, 4]]
x_data = torch.tensor(data)

x_ones = torch.ones_like(x_data) # retains the properties of x_data
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # overrides the datatype of x_data
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.1043, 0.5273],
        [0.2968, 0.1281]]) 



In [7]:
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Shape of tensor: {rand_tensor.shape}")
print(f"Datatype of tensor: {rand_tensor.dtype}")
print(f"Device tensor is stored on: {rand_tensor.device}")

Shape of tensor: torch.Size([2, 3])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [11]:
if torch.cuda.is_available():
    print('yé')
    tensor = rand_tensor.to('cuda')

In [16]:
print(rand_tensor)
print(f"tensor.mul(tensor) \n {rand_tensor.mul(rand_tensor)} \n")
# Alternative syntax:
print(f"tensor * tensor \n {rand_tensor * ones_tensor}")

print(f"tensor.matmul(tensor.T) \n {rand_tensor.matmul(rand_tensor.T)} \n")
# Alternative syntax:
print(f"tensor @ tensor.T \n {ones_tensor.T @ rand_tensor}")

tensor([[0.2971, 0.4078, 0.7166],
        [0.7357, 0.1258, 0.5945]])
tensor.mul(tensor) 
 tensor([[0.0883, 0.1663, 0.5135],
        [0.5412, 0.0158, 0.3534]]) 

tensor * tensor 
 tensor([[0.2971, 0.4078, 0.7166],
        [0.7357, 0.1258, 0.5945]])
tensor.matmul(tensor.T) 
 tensor([[0.7681, 0.6959],
        [0.6959, 0.9105]]) 

tensor @ tensor.T 
 tensor([[1.0328, 0.5336, 1.3111],
        [1.0328, 0.5336, 1.3111],
        [1.0328, 0.5336, 1.3111]])
